# Generated by Django 4.1.7 on 2023-03-16 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_work'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='thumnall',
            new_name='thumbnall',
        ),
    ]
